export default[
    {
         img : "/./images/anabelle.jpg",
         name : "Annabelle Comes Home",
         year : "2019",
         genre : "Supernatural, Horror",
         director:"Gary Dauberman",
         rating : 5.9,
         myrating : 8.0,
         description : "Annabelle Comes Home is a chilling addition to the Conjuring Universe, unleashing supernatural terror as the malevolent doll wreaks havoc on a hapless babysitter and her friends.",
         link : "https://en.wikipedia.org/wiki/Annabelle_Comes_Home",
    },
    {
         img : "/./images/the nun.jpg",
         name : "The Nun",
         year : "2018",
         genre : "Gothic, Supernatural, Horror",
         director:"Corin Hardy",
         rating : 5.3,
         myrating : 8.1,
         description : "The Nun plunges audiences into the darkest corners of the Conjuring Universe, where a malevolent presence terrorizes a remote Romanian abbey.",
         link : "https://en.wikipedia.org/wiki/The_Nun_(2018_film)",
    },
    {
         img : "/./images/babadook.jpg",
         name : "The Babadook",
         year : "2014",
         genre : "Horror",
         director:"Jennifer Kent",
         rating : 6.8,
         myrating : 8.0,
         description : "The Babadook is a psychological horror masterpiece that delves deep into the unraveling psyche of a grieving mother and her troubled son. ",
         link : "https://en.wikipedia.org/wiki/The_Babadook",
    },
    {
         img: "/./images/evildead.jpg",
         name : "Evil Dead Rise",
         year : "2023",
         genre : "Supernatural, Horror",
         director:"Lee Cronin",
         rating : 6.6,
         myrating : 7.9,
         description : "The Babadook is a psychological horror masterpiece that delves deep into the unraveling psyche of a grieving mother and her troubled son. ",
         link : "https://en.wikipedia.org/wiki/Evil_Dead_Rise",
    }

]